//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Csharper.OliverTwist.GateService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GateService.IADEService")]
    public interface IADEService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IADEService/Login", ReplyAction="http://tempuri.org/IADEService/LoginResponse")]
        string Login([System.ServiceModel.MessageParameterAttribute(Name="login")] string login1, string password, string senderName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IADEService/SendSms", ReplyAction="http://tempuri.org/IADEService/SendSmsResponse")]
        System.Collections.Generic.List<Csharper.Common.SMSSeriesId> SendSms(string sessionKey, System.Collections.Generic.List<string> addresses, string message, string clientId, string distibutionId, string messageId, bool transliterate, System.Nullable<System.DateTime> deliveryTime, System.Nullable<System.TimeSpan> validalityPeriod, System.Collections.Generic.Dictionary<string, string> customParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IADEService/CheckSMSStatuses", ReplyAction="http://tempuri.org/IADEService/CheckSMSStatusesResponse")]
        System.Collections.Generic.List<Csharper.Common.SMSCheckItem> CheckSMSStatuses(string sessionKey, string clientId, string distributionId, System.Nullable<System.DateTime> dateStart, System.Nullable<System.DateTime> dateEnd, System.Nullable<long> rowsPerPage, System.Nullable<long> pageNumber, System.Collections.Generic.Dictionary<string, string> customLimits);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IADEService/GetSMSCounters", ReplyAction="http://tempuri.org/IADEService/GetSMSCountersResponse")]
        System.Collections.Generic.List<Csharper.Common.SMSCounter> GetSMSCounters(string sessionKey, System.Nullable<Csharper.Common.SMSStatus> status, string clientId, string distibutionId, System.Nullable<System.DateTime> dateStart, System.Nullable<System.DateTime> dateEnd, System.Collections.Generic.Dictionary<string, string> customLimits);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IADEService/GetSMSDetalization", ReplyAction="http://tempuri.org/IADEService/GetSMSDetalizationResponse")]
        System.Collections.Generic.List<Csharper.Common.SMSDetail> GetSMSDetalization(string sessionKey, string clientId, string distibutionId, string extSmsId, System.Nullable<System.Guid> id, System.Nullable<System.DateTime> dateStart, System.Nullable<System.DateTime> dateEnd, System.Nullable<long> rowsPerPage, System.Nullable<long> pageNumber, System.Collections.Generic.Dictionary<string, string> customLimits);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IADEService/CheckSMSByMessageId", ReplyAction="http://tempuri.org/IADEService/CheckSMSByMessageIdResponse")]
        System.Collections.Generic.List<Csharper.Common.SMSCheckItem> CheckSMSByMessageId(string sessionKey, string messageId, System.Nullable<long> rowsPerPage, System.Nullable<long> pageNumber, string clientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IADEService/CheckSMSById", ReplyAction="http://tempuri.org/IADEService/CheckSMSByIdResponse")]
        Csharper.Common.SMSCheckItem CheckSMSById(string sessionKey, System.Guid id, string clientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IADEService/CheckSMS", ReplyAction="http://tempuri.org/IADEService/CheckSMSResponse")]
        Csharper.Common.SMSCheckItem CheckSMS(string login, string password, System.Guid Id, string clientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IADEService/LogOff", ReplyAction="http://tempuri.org/IADEService/LogOffResponse")]
        void LogOff(string sessionKey);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IADEServiceChannel : Csharper.OliverTwist.GateService.IADEService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ADEServiceClient : System.ServiceModel.ClientBase<Csharper.OliverTwist.GateService.IADEService>, Csharper.OliverTwist.GateService.IADEService {
        
        public ADEServiceClient() {
        }
        
        public ADEServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ADEServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ADEServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ADEServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Login(string login1, string password, string senderName) {
            return base.Channel.Login(login1, password, senderName);
        }
        
        public System.Collections.Generic.List<Csharper.Common.SMSSeriesId> SendSms(string sessionKey, System.Collections.Generic.List<string> addresses, string message, string clientId, string distibutionId, string messageId, bool transliterate, System.Nullable<System.DateTime> deliveryTime, System.Nullable<System.TimeSpan> validalityPeriod, System.Collections.Generic.Dictionary<string, string> customParameters) {
            return base.Channel.SendSms(sessionKey, addresses, message, clientId, distibutionId, messageId, transliterate, deliveryTime, validalityPeriod, customParameters);
        }
        
        public System.Collections.Generic.List<Csharper.Common.SMSCheckItem> CheckSMSStatuses(string sessionKey, string clientId, string distributionId, System.Nullable<System.DateTime> dateStart, System.Nullable<System.DateTime> dateEnd, System.Nullable<long> rowsPerPage, System.Nullable<long> pageNumber, System.Collections.Generic.Dictionary<string, string> customLimits) {
            return base.Channel.CheckSMSStatuses(sessionKey, clientId, distributionId, dateStart, dateEnd, rowsPerPage, pageNumber, customLimits);
        }
        
        public System.Collections.Generic.List<Csharper.Common.SMSCounter> GetSMSCounters(string sessionKey, System.Nullable<Csharper.Common.SMSStatus> status, string clientId, string distibutionId, System.Nullable<System.DateTime> dateStart, System.Nullable<System.DateTime> dateEnd, System.Collections.Generic.Dictionary<string, string> customLimits) {
            return base.Channel.GetSMSCounters(sessionKey, status, clientId, distibutionId, dateStart, dateEnd, customLimits);
        }
        
        public System.Collections.Generic.List<Csharper.Common.SMSDetail> GetSMSDetalization(string sessionKey, string clientId, string distibutionId, string extSmsId, System.Nullable<System.Guid> id, System.Nullable<System.DateTime> dateStart, System.Nullable<System.DateTime> dateEnd, System.Nullable<long> rowsPerPage, System.Nullable<long> pageNumber, System.Collections.Generic.Dictionary<string, string> customLimits) {
            return base.Channel.GetSMSDetalization(sessionKey, clientId, distibutionId, extSmsId, id, dateStart, dateEnd, rowsPerPage, pageNumber, customLimits);
        }
        
        public System.Collections.Generic.List<Csharper.Common.SMSCheckItem> CheckSMSByMessageId(string sessionKey, string messageId, System.Nullable<long> rowsPerPage, System.Nullable<long> pageNumber, string clientId) {
            return base.Channel.CheckSMSByMessageId(sessionKey, messageId, rowsPerPage, pageNumber, clientId);
        }
        
        public Csharper.Common.SMSCheckItem CheckSMSById(string sessionKey, System.Guid id, string clientId) {
            return base.Channel.CheckSMSById(sessionKey, id, clientId);
        }
        
        public Csharper.Common.SMSCheckItem CheckSMS(string login, string password, System.Guid Id, string clientId) {
            return base.Channel.CheckSMS(login, password, Id, clientId);
        }
        
        public void LogOff(string sessionKey) {
            base.Channel.LogOff(sessionKey);
        }
    }
}
