//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.1.
// 
#pragma warning disable 1591

namespace Csharper.SMSServiceGate.ADEService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IADEService", Namespace="http://tempuri.org/")]
    public partial class ADEService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback LoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendSmsOperationCompleted;
        
        private System.Threading.SendOrPostCallback CheckSMSByDistributionOperationCompleted;
        
        private System.Threading.SendOrPostCallback CheckSMSByMessageIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback CheckSMSByIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback CheckSMSOperationCompleted;
        
        private System.Threading.SendOrPostCallback LogOffOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ADEService() {
            this.Url = global::Csharper.SMSServiceGate.Properties.Settings.Default.SMSServiceGate_ADEService_ADEService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event LoginCompletedEventHandler LoginCompleted;
        
        /// <remarks/>
        public event SendSmsCompletedEventHandler SendSmsCompleted;
        
        /// <remarks/>
        public event CheckSMSByDistributionCompletedEventHandler CheckSMSByDistributionCompleted;
        
        /// <remarks/>
        public event CheckSMSByMessageIdCompletedEventHandler CheckSMSByMessageIdCompleted;
        
        /// <remarks/>
        public event CheckSMSByIdCompletedEventHandler CheckSMSByIdCompleted;
        
        /// <remarks/>
        public event CheckSMSCompletedEventHandler CheckSMSCompleted;
        
        /// <remarks/>
        public event LogOffCompletedEventHandler LogOffCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IADEService/Login", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Login([System.Xml.Serialization.XmlElementAttribute("login", IsNullable=true)] string login1, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string password, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string senderName) {
            object[] results = this.Invoke("Login", new object[] {
                        login1,
                        password,
                        senderName});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void LoginAsync(string login1, string password, string senderName) {
            this.LoginAsync(login1, password, senderName, null);
        }
        
        /// <remarks/>
        public void LoginAsync(string login1, string password, string senderName, object userState) {
            if ((this.LoginOperationCompleted == null)) {
                this.LoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoginOperationCompleted);
            }
            this.InvokeAsync("Login", new object[] {
                        login1,
                        password,
                        senderName}, this.LoginOperationCompleted, userState);
        }
        
        private void OnLoginOperationCompleted(object arg) {
            if ((this.LoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoginCompleted(this, new LoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IADEService/SendSms", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Csharper.Common", IsNullable=false)]
        public SMSSeriesId[] SendSms([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string sessionKey, [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)] [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")] string[] addresses, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string message, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string distibutionId, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string messageId, bool transliterate, [System.Xml.Serialization.XmlIgnoreAttribute()] bool transliterateSpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<System.DateTime> deliveryTime, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool deliveryTimeSpecified, [System.Xml.Serialization.XmlElementAttribute(DataType="duration", IsNullable=true)] string validalityPeriod) {
            object[] results = this.Invoke("SendSms", new object[] {
                        sessionKey,
                        addresses,
                        message,
                        distibutionId,
                        messageId,
                        transliterate,
                        transliterateSpecified,
                        deliveryTime,
                        deliveryTimeSpecified,
                        validalityPeriod});
            return ((SMSSeriesId[])(results[0]));
        }
        
        /// <remarks/>
        public void SendSmsAsync(string sessionKey, string[] addresses, string message, string distibutionId, string messageId, bool transliterate, bool transliterateSpecified, System.Nullable<System.DateTime> deliveryTime, bool deliveryTimeSpecified, string validalityPeriod) {
            this.SendSmsAsync(sessionKey, addresses, message, distibutionId, messageId, transliterate, transliterateSpecified, deliveryTime, deliveryTimeSpecified, validalityPeriod, null);
        }
        
        /// <remarks/>
        public void SendSmsAsync(string sessionKey, string[] addresses, string message, string distibutionId, string messageId, bool transliterate, bool transliterateSpecified, System.Nullable<System.DateTime> deliveryTime, bool deliveryTimeSpecified, string validalityPeriod, object userState) {
            if ((this.SendSmsOperationCompleted == null)) {
                this.SendSmsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendSmsOperationCompleted);
            }
            this.InvokeAsync("SendSms", new object[] {
                        sessionKey,
                        addresses,
                        message,
                        distibutionId,
                        messageId,
                        transliterate,
                        transliterateSpecified,
                        deliveryTime,
                        deliveryTimeSpecified,
                        validalityPeriod}, this.SendSmsOperationCompleted, userState);
        }
        
        private void OnSendSmsOperationCompleted(object arg) {
            if ((this.SendSmsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendSmsCompleted(this, new SendSmsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IADEService/CheckSMSByDistribution", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Csharper.Common")]
        public SMSCheckItem[] CheckSMSByDistribution([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string sessionKey, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string distributionId, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<long> rowsPerPage, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool rowsPerPageSpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<long> pageNumber, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool pageNumberSpecified) {
            object[] results = this.Invoke("CheckSMSByDistribution", new object[] {
                        sessionKey,
                        distributionId,
                        rowsPerPage,
                        rowsPerPageSpecified,
                        pageNumber,
                        pageNumberSpecified});
            return ((SMSCheckItem[])(results[0]));
        }
        
        /// <remarks/>
        public void CheckSMSByDistributionAsync(string sessionKey, string distributionId, System.Nullable<long> rowsPerPage, bool rowsPerPageSpecified, System.Nullable<long> pageNumber, bool pageNumberSpecified) {
            this.CheckSMSByDistributionAsync(sessionKey, distributionId, rowsPerPage, rowsPerPageSpecified, pageNumber, pageNumberSpecified, null);
        }
        
        /// <remarks/>
        public void CheckSMSByDistributionAsync(string sessionKey, string distributionId, System.Nullable<long> rowsPerPage, bool rowsPerPageSpecified, System.Nullable<long> pageNumber, bool pageNumberSpecified, object userState) {
            if ((this.CheckSMSByDistributionOperationCompleted == null)) {
                this.CheckSMSByDistributionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckSMSByDistributionOperationCompleted);
            }
            this.InvokeAsync("CheckSMSByDistribution", new object[] {
                        sessionKey,
                        distributionId,
                        rowsPerPage,
                        rowsPerPageSpecified,
                        pageNumber,
                        pageNumberSpecified}, this.CheckSMSByDistributionOperationCompleted, userState);
        }
        
        private void OnCheckSMSByDistributionOperationCompleted(object arg) {
            if ((this.CheckSMSByDistributionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckSMSByDistributionCompleted(this, new CheckSMSByDistributionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IADEService/CheckSMSByMessageId", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Csharper.Common")]
        public SMSCheckItem[] CheckSMSByMessageId([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string sessionKey, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string messageId, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<long> rowsPerPage, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool rowsPerPageSpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<long> pageNumber, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool pageNumberSpecified) {
            object[] results = this.Invoke("CheckSMSByMessageId", new object[] {
                        sessionKey,
                        messageId,
                        rowsPerPage,
                        rowsPerPageSpecified,
                        pageNumber,
                        pageNumberSpecified});
            return ((SMSCheckItem[])(results[0]));
        }
        
        /// <remarks/>
        public void CheckSMSByMessageIdAsync(string sessionKey, string messageId, System.Nullable<long> rowsPerPage, bool rowsPerPageSpecified, System.Nullable<long> pageNumber, bool pageNumberSpecified) {
            this.CheckSMSByMessageIdAsync(sessionKey, messageId, rowsPerPage, rowsPerPageSpecified, pageNumber, pageNumberSpecified, null);
        }
        
        /// <remarks/>
        public void CheckSMSByMessageIdAsync(string sessionKey, string messageId, System.Nullable<long> rowsPerPage, bool rowsPerPageSpecified, System.Nullable<long> pageNumber, bool pageNumberSpecified, object userState) {
            if ((this.CheckSMSByMessageIdOperationCompleted == null)) {
                this.CheckSMSByMessageIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckSMSByMessageIdOperationCompleted);
            }
            this.InvokeAsync("CheckSMSByMessageId", new object[] {
                        sessionKey,
                        messageId,
                        rowsPerPage,
                        rowsPerPageSpecified,
                        pageNumber,
                        pageNumberSpecified}, this.CheckSMSByMessageIdOperationCompleted, userState);
        }
        
        private void OnCheckSMSByMessageIdOperationCompleted(object arg) {
            if ((this.CheckSMSByMessageIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckSMSByMessageIdCompleted(this, new CheckSMSByMessageIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IADEService/CheckSMSById", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public SMSCheckItem CheckSMSById([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string sessionKey, string id) {
            object[] results = this.Invoke("CheckSMSById", new object[] {
                        sessionKey,
                        id});
            return ((SMSCheckItem)(results[0]));
        }
        
        /// <remarks/>
        public void CheckSMSByIdAsync(string sessionKey, string id) {
            this.CheckSMSByIdAsync(sessionKey, id, null);
        }
        
        /// <remarks/>
        public void CheckSMSByIdAsync(string sessionKey, string id, object userState) {
            if ((this.CheckSMSByIdOperationCompleted == null)) {
                this.CheckSMSByIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckSMSByIdOperationCompleted);
            }
            this.InvokeAsync("CheckSMSById", new object[] {
                        sessionKey,
                        id}, this.CheckSMSByIdOperationCompleted, userState);
        }
        
        private void OnCheckSMSByIdOperationCompleted(object arg) {
            if ((this.CheckSMSByIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckSMSByIdCompleted(this, new CheckSMSByIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IADEService/CheckSMS", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public SMSCheckItem CheckSMS([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string login, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string password, string Id) {
            object[] results = this.Invoke("CheckSMS", new object[] {
                        login,
                        password,
                        Id});
            return ((SMSCheckItem)(results[0]));
        }
        
        /// <remarks/>
        public void CheckSMSAsync(string login, string password, string Id) {
            this.CheckSMSAsync(login, password, Id, null);
        }
        
        /// <remarks/>
        public void CheckSMSAsync(string login, string password, string Id, object userState) {
            if ((this.CheckSMSOperationCompleted == null)) {
                this.CheckSMSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckSMSOperationCompleted);
            }
            this.InvokeAsync("CheckSMS", new object[] {
                        login,
                        password,
                        Id}, this.CheckSMSOperationCompleted, userState);
        }
        
        private void OnCheckSMSOperationCompleted(object arg) {
            if ((this.CheckSMSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckSMSCompleted(this, new CheckSMSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IADEService/LogOff", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void LogOff([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string sessionKey) {
            this.Invoke("LogOff", new object[] {
                        sessionKey});
        }
        
        /// <remarks/>
        public void LogOffAsync(string sessionKey) {
            this.LogOffAsync(sessionKey, null);
        }
        
        /// <remarks/>
        public void LogOffAsync(string sessionKey, object userState) {
            if ((this.LogOffOperationCompleted == null)) {
                this.LogOffOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLogOffOperationCompleted);
            }
            this.InvokeAsync("LogOff", new object[] {
                        sessionKey}, this.LogOffOperationCompleted, userState);
        }
        
        private void OnLogOffOperationCompleted(object arg) {
            if ((this.LogOffCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LogOffCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Csharper.Common")]
    public partial class SMSSeriesId {
        
        private string externalIdField;
        
        private string idField;
        
        private int seriesPositionField;
        
        private bool seriesPositionFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ExternalId {
            get {
                return this.externalIdField;
            }
            set {
                this.externalIdField = value;
            }
        }
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int SeriesPosition {
            get {
                return this.seriesPositionField;
            }
            set {
                this.seriesPositionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SeriesPositionSpecified {
            get {
                return this.seriesPositionFieldSpecified;
            }
            set {
                this.seriesPositionFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Csharper.Common")]
    public partial class SMSCheckItem {
        
        private string idField;
        
        private System.DateTime lastCheckUTCField;
        
        private bool lastCheckUTCFieldSpecified;
        
        private string messageIdField;
        
        private SMSStatus statusField;
        
        private bool statusFieldSpecified;
        
        /// <remarks/>
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime LastCheckUTC {
            get {
                return this.lastCheckUTCField;
            }
            set {
                this.lastCheckUTCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LastCheckUTCSpecified {
            get {
                return this.lastCheckUTCFieldSpecified;
            }
            set {
                this.lastCheckUTCFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MessageId {
            get {
                return this.messageIdField;
            }
            set {
                this.messageIdField = value;
            }
        }
        
        /// <remarks/>
        public SMSStatus Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StatusSpecified {
            get {
                return this.statusFieldSpecified;
            }
            set {
                this.statusFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Csharper.Common")]
    public enum SMSStatus {
        
        /// <remarks/>
        InQueue,
        
        /// <remarks/>
        Send,
        
        /// <remarks/>
        Delivered,
        
        /// <remarks/>
        SendError,
        
        /// <remarks/>
        ValidationError,
        
        /// <remarks/>
        Cancelled,
        
        /// <remarks/>
        CancellationPending,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void LoginCompletedEventHandler(object sender, LoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void SendSmsCompletedEventHandler(object sender, SendSmsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendSmsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendSmsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SMSSeriesId[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SMSSeriesId[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void CheckSMSByDistributionCompletedEventHandler(object sender, CheckSMSByDistributionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckSMSByDistributionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckSMSByDistributionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SMSCheckItem[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SMSCheckItem[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void CheckSMSByMessageIdCompletedEventHandler(object sender, CheckSMSByMessageIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckSMSByMessageIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckSMSByMessageIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SMSCheckItem[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SMSCheckItem[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void CheckSMSByIdCompletedEventHandler(object sender, CheckSMSByIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckSMSByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckSMSByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SMSCheckItem Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SMSCheckItem)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void CheckSMSCompletedEventHandler(object sender, CheckSMSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckSMSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckSMSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SMSCheckItem Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SMSCheckItem)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void LogOffCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591